# theme: jekyll-theme-cayman # jekyll-theme-cayman
title: Customer ID Capture
description: Scan machine readable identity cards and forward to cloud
show_releases: true
release_url: https://github.com/tony-mowers/pos_id_capture/releases/latest
repository: tony-mowers/pos_id_capture
baseurl: /pos_id_capture

# Build Settings
sass:
  sass_dir: _sass
